/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#0c0e14",
        "surface-container-low": "#11131a",
        "tertiary-dim": "#ef9b4b",
        "secondary-fixed-dim": "#ebadff",
        "on-error-container": "#ffb2b9",
        "on-tertiary-fixed-variant": "#653600",
        "on-surface-variant": "#aaaab3",
        "on-secondary-container": "#f1bfff",
        "inverse-primary": "#1854d7",
        "surface-container-highest": "#23262f",
        "surface-bright": "#292c36",
        "on-primary": "#002776",
        "on-tertiary-fixed": "#391c00",
        "on-secondary": "#4c0068",
        "tertiary-fixed-dim": "#ef9b4b",
        "primary-container": "#7d9cff",
        "tertiary-container": "#ffa857",
        "primary": "#91abff",
        "outline": "#74757d",
        "surface-container": "#171921",
        "on-primary-fixed": "#000000",
        "secondary-dim": "#ce7eec",
        "error": "#ff6e84",
        "surface-container-high": "#1d1f28",
        "on-primary-container": "#001d5c",
        "on-primary-fixed-variant": "#002571",
        "on-secondary-fixed-variant": "#792c97",
        "inverse-on-surface": "#53555c",
        "surface-container-lowest": "#000000",
        "on-secondary-fixed": "#580078",
        "error-container": "#a70138",
        "secondary": "#dd8bfb",
        "tertiary": "#ffbb81",
        "outline-variant": "#46484f",
        "primary-fixed-dim": "#688dff",
        "error-dim": "#d73357",
        "on-error": "#490013",
        "inverse-surface": "#faf8ff",
        "on-surface": "#eaeaf3",
        "surface-tint": "#91abff",
        "on-tertiary": "#653600",
        "primary-dim": "#396bee",
        "tertiary-fixed": "#ffa857",
        "on-tertiary-container": "#582e00",
        "primary-fixed": "#7d9cff",
        "surface-variant": "#23262f",
        "surface": "#0c0e14",
        "secondary-fixed": "#f2c1ff",
        "on-background": "#eaeaf3",
        "background": "#0c0e14",
        "secondary-container": "#6e208c"
      },
      fontFamily: {
        "headline": ["Syne", "sans-serif"],
        "body": ["DM Sans", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "brand": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
